# AWS Access Key Patterns
title = "AWS Access Keys"

[[rules]]
id = "aws-access-key"
description = "AWS Access Key ID"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
keywords = ["akia","aws"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws(.{0,20})?(''|"){0,1}[0-9a-zA-Z/+]{40}(''|"){0,1}'''
keywords = ["aws","secret","key"]

[[rules]]
id = "aws-session-token"
description = "AWS Session Token"
regex = '''(?i)[(]?"aws.*session.*token[)" ]{0,25}=[: ]{0,5}[A-Za-z0-9/+=]{16,128}'''
keywords = ["aws","session","token"]
